# Generated by Django 4.2.25 on 2025-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='messageNbr',
            field=models.IntegerField(default=0),
        ),
    ]
