# Generated by Django 4.2.25 on 2025-11-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_messagenbr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='messageNbr',
        ),
    ]
