# Generated by Django 4.2.25 on 2025-11-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentai',
            name='image',
            field=models.ImageField(default='default-AI.jpg', upload_to='agent_images/'),
        ),
    ]
