# Generated by Django 4.2.25 on 2025-11-17 18:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agentAI', '0002_alter_agentai_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgentAI',
            new_name='AIAgent',
        ),
    ]
