# Generated by Django 4.2.25 on 2025-11-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0003_rename_agentai_aiagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='discussion',
            field=models.TextField(default=''),
        ),
    ]
