# Generated by Django 4.2.25 on 2025-11-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0004_aiagent_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='cooldown',
            field=models.IntegerField(default=0),
        ),
    ]
