# Generated by Django 4.2.25 on 2025-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0005_aiagent_description_alter_aiagent_cooldown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='model',
            field=models.CharField(choices=[('api', 'API'), ('local', 'Local')], default='api', max_length=100),
        ),
    ]
