# Generated by Django 4.2.25 on 2025-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0006_alter_aiagent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='model',
            field=models.CharField(choices=[('API', 'API'), ('Local', 'Local')], default='api', max_length=100),
        ),
    ]
