# Generated by Django 4.2.25 on 2025-11-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0007_alter_aiagent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='description',
            field=models.TextField(default='You are an AI that answers questions.'),
        ),
    ]
