# Generated by Django 4.2.25 on 2025-11-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0009_alter_aiagent_description_alter_aiagent_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='discussion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='aiagent',
            name='prompt',
            field=models.TextField(default='You are an AI that answers questions.'),
        ),
    ]
