# Generated by Django 4.2.25 on 2025-11-24 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0010_alter_aiagent_discussion_alter_aiagent_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagent',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
