# Generated by Django 4.2.25 on 2025-11-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0011_aiagent_last_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiagent',
            old_name='prompt',
            new_name='initial_prompt',
        ),
    ]
