# Generated by Django 4.2.25 on 2025-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentAI', '0012_rename_prompt_aiagent_initial_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagent',
            name='model',
            field=models.CharField(choices=[('API', 'API'), ('Local', 'Local')], default='API', max_length=100),
        ),
    ]
