# Generated by Django 4.2.25 on 2025-10-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
